Documentation:
  Enabled: false

Metrics/CyclomaticComplexity:
  Exclude:
    - "bin/bundle"

Metrics/MethodLength:
  Exclude:
    - "bin/bundle"

Layout/LineLength:
  Exclude:
    - "bin/bundle"

Metrics/PerceivedComplexity:
  Exclude:
    - "bin/bundle"